name: Build and Release

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build Plugin
        run: |
          chmod +x gradlew
          ./gradlew make
          
      - name: Push builds
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://github.com/azrailankara/ddizi-extension.git
          cd ddizi-extension
          git checkout -b builds
          cp ../build/repos/* .
          git add .
          git commit -m "Build $GITHUB_SHA"
          git push origin builds --force 