name: Build and Release

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Plugin
        run: |
          ./gradlew make
          
      - name: Push Builds
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git checkout --orphan builds
          git reset --hard
          cp -r build/repos/* .
          git add .
          git commit -m "Build $GITHUB_SHA"
          git push -f origin builds 