name: Build and Release

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Build Plugin
        run: |
          chmod +x gradlew
          ./gradlew make
          
      - name: Push builds
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          cd $(basename ${{ github.repository }})
          git checkout -b builds || git checkout builds
          cp -r ../build/repos/* .
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push -f origin builds 